### ISSUE TITLE
Add larger fonts

### ISSUE THREAD

**Issue by pdp7** [ayoy/micropython-waveshare-epd#1]
Would it be possible to add larger fonts that font24?

Thank you!

**Comment by ayoy** [comment]
Hi, yes, it's possible and you can do it with little effort. There's an app for it described here:
https://luckyresistor.me/2015/09/04/convert-bitmap-fonts-for-lcd-displays-with-style

And since the app is for OS X only, I ported it to C++ here:
https://github.com/ayoy/font2bytes

There's a GUI app using Qt, and a command-line app that depends only on libpng. I didn't have time to write about it on a blog, but otherwise it should work. Please refer to the original blog post from Lucky Resistor on how to generate an input image.

Cheers!
